spring:
  application:
    name: lovable-clone
    description: This is a lovable clone application

  datasource:
    url: jdbc:postgresql://localhost:5432/lovableclone
    username: mayurigoswami

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
